name: Run tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: go test
        run: |
          go test ./...